version: '3'
services:
  db:
    image: mysql:9.1.0
    container_name: steradian
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
