version: '3'
services:
  db:
    image: postgres:16.8-alpine3.20
    container_name: steradian
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=laravel
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
